import type { Skill, Bundle, Workflow } from "./types";

export const skills: Skill[] = [
  { id: "auto-debug-tracer", name: "Auto Debug Tracer", description: "Automatically traces through stack traces and identifies root cause of runtime errors with contextual fix suggestions.", author: "alexchen", tags: ["debugging", "error-handling", "tracing"], supportedTools: ["Claude Code", "Cursor", "Codex CLI"], language: "Python", category: "debugging", installCommands: { "Claude Code": "claude skill install auto-debug-tracer", "Cursor": "cursor ext install auto-debug-tracer", "Codex CLI": "codex install auto-debug-tracer" }, usageExample: "# Paste a stack trace and run:\nauto-debug-tracer analyze --file app.py --line 42", stars: 892, downloads: 14200, featured: true },
  { id: "smart-refactor", name: "Smart Refactor", description: "Intelligently refactors code by detecting code smells, extracting functions, and applying SOLID principles automatically.", author: "sarahdev", tags: ["refactoring", "clean-code", "solid"], supportedTools: ["Claude Code", "Cursor", "Gemini CLI"], language: "TypeScript", category: "refactoring", installCommands: { "Claude Code": "claude skill install smart-refactor", "Cursor": "cursor ext install smart-refactor", "Gemini CLI": "gemini install smart-refactor" }, usageExample: "smart-refactor --target src/components/ --rules solid,dry", stars: 1243, downloads: 22100, featured: true },
  { id: "test-gen-pro", name: "Test Generator Pro", description: "Generates comprehensive unit, integration, and e2e tests with edge cases, mocks, and fixtures.", author: "testmaster", tags: ["testing", "unit-tests", "coverage"], supportedTools: ["Claude Code", "Cursor", "Codex CLI", "Antigravity"], language: "Multi", category: "testing", installCommands: { "Claude Code": "claude skill install test-gen-pro", "Cursor": "cursor ext install test-gen-pro", "Codex CLI": "codex install test-gen-pro", "Antigravity": "ag install test-gen-pro" }, usageExample: "test-gen-pro generate --file src/auth.ts --framework vitest", stars: 2105, downloads: 35600, featured: true },
  { id: "api-scaffolder", name: "API Scaffolder", description: "Scaffolds REST and GraphQL APIs from natural language descriptions, including models, routes, validation, and docs.", author: "devcraft", tags: ["api", "scaffolding", "rest", "graphql"], supportedTools: ["Claude Code", "Codex CLI", "Gemini CLI"], language: "Python", category: "code-generation", installCommands: { "Claude Code": "claude skill install api-scaffolder", "Codex CLI": "codex install api-scaffolder", "Gemini CLI": "gemini install api-scaffolder" }, usageExample: "api-scaffolder create --spec 'User CRUD with auth' --framework fastapi", stars: 1567, downloads: 28300, featured: true },
  { id: "docstring-wizard", name: "Docstring Wizard", description: "Auto-generates comprehensive docstrings, type hints, and inline comments following Google/NumPy/Sphinx conventions.", author: "docwriter", tags: ["documentation", "docstrings", "type-hints"], supportedTools: ["Claude Code", "Cursor", "Antigravity"], language: "Python", category: "documentation", installCommands: { "Claude Code": "claude skill install docstring-wizard", "Cursor": "cursor ext install docstring-wizard", "Antigravity": "ag install docstring-wizard" }, usageExample: "docstring-wizard annotate --dir src/ --style google", stars: 734, downloads: 11800 },
  { id: "ci-pipeline-gen", name: "CI Pipeline Generator", description: "Creates GitHub Actions, GitLab CI, or CircleCI pipelines from project analysis with caching, matrix builds, and deploy steps.", author: "opsmaster", tags: ["ci-cd", "github-actions", "devops"], supportedTools: ["Claude Code", "Codex CLI"], language: "Multi", category: "devops", installCommands: { "Claude Code": "claude skill install ci-pipeline-gen", "Codex CLI": "codex install ci-pipeline-gen" }, usageExample: "ci-pipeline-gen --platform github --lang python --deploy aws", stars: 956, downloads: 16400 },
  { id: "sql-optimizer", name: "SQL Query Optimizer", description: "Analyzes SQL queries for performance issues, suggests indexes, rewrites slow queries, and explains execution plans.", author: "dbpro", tags: ["sql", "optimization", "database"], supportedTools: ["Claude Code", "Cursor", "Gemini CLI"], language: "Multi", category: "performance", installCommands: { "Claude Code": "claude skill install sql-optimizer", "Cursor": "cursor ext install sql-optimizer", "Gemini CLI": "gemini install sql-optimizer" }, usageExample: "sql-optimizer analyze --query 'SELECT * FROM orders JOIN...'", stars: 1089, downloads: 19500 },
  { id: "security-scanner", name: "Security Scanner", description: "Scans code for OWASP Top 10 vulnerabilities, dependency CVEs, secrets leaks, and generates remediation reports.", author: "secteam", tags: ["security", "vulnerability", "owasp"], supportedTools: ["Claude Code", "Cursor", "Codex CLI", "Gemini CLI", "Antigravity"], language: "Multi", category: "security", installCommands: { "Claude Code": "claude skill install security-scanner", "Cursor": "cursor ext install security-scanner", "Codex CLI": "codex install security-scanner", "Gemini CLI": "gemini install security-scanner", "Antigravity": "ag install security-scanner" }, usageExample: "security-scanner scan --dir . --report html", stars: 1876, downloads: 31200, featured: true },
  { id: "data-pipeline-builder", name: "Data Pipeline Builder", description: "Creates ETL/ELT pipelines with data validation, transformation steps, and scheduling using Airflow or Prefect.", author: "dataeng", tags: ["etl", "data-pipeline", "airflow"], supportedTools: ["Claude Code", "Codex CLI"], language: "Python", category: "data", installCommands: { "Claude Code": "claude skill install data-pipeline-builder", "Codex CLI": "codex install data-pipeline-builder" }, usageExample: "data-pipeline-builder create --source postgres --dest s3 --transform normalize", stars: 678, downloads: 9800 },
  { id: "arch-diagrammer", name: "Architecture Diagrammer", description: "Generates architecture diagrams from codebase analysis using Mermaid, PlantUML, or D2 with auto-detected relationships.", author: "archviz", tags: ["architecture", "diagrams", "visualization"], supportedTools: ["Claude Code", "Cursor", "Gemini CLI"], language: "Multi", category: "architecture", installCommands: { "Claude Code": "claude skill install arch-diagrammer", "Cursor": "cursor ext install arch-diagrammer", "Gemini CLI": "gemini install arch-diagrammer" }, usageExample: "arch-diagrammer generate --dir src/ --format mermaid", stars: 1432, downloads: 24100, featured: true },
  { id: "regex-builder", name: "Regex Builder", description: "Converts natural language descriptions into regex patterns with test cases and explanations.", author: "patterndev", tags: ["regex", "parsing", "text-processing"], supportedTools: ["Claude Code", "Cursor"], language: "Multi", category: "code-generation", installCommands: { "Claude Code": "claude skill install regex-builder", "Cursor": "cursor ext install regex-builder" }, usageExample: "regex-builder 'match email addresses with .edu domain'", stars: 521, downloads: 8200 },
  { id: "perf-profiler", name: "Performance Profiler", description: "Profiles Python/JS applications, identifies bottlenecks, memory leaks, and suggests optimization strategies.", author: "speeddev", tags: ["profiling", "memory", "optimization"], supportedTools: ["Claude Code", "Codex CLI", "Antigravity"], language: "Python", category: "performance", installCommands: { "Claude Code": "claude skill install perf-profiler", "Codex CLI": "codex install perf-profiler", "Antigravity": "ag install perf-profiler" }, usageExample: "perf-profiler run --file server.py --mode memory", stars: 845, downloads: 13600 },
  { id: "migration-assistant", name: "DB Migration Assistant", description: "Generates safe database migrations with rollback scripts, data preservation checks, and zero-downtime strategies.", author: "migratepro", tags: ["migration", "database", "schema"], supportedTools: ["Claude Code", "Cursor", "Codex CLI"], language: "Python", category: "data", installCommands: { "Claude Code": "claude skill install migration-assistant", "Cursor": "cursor ext install migration-assistant", "Codex CLI": "codex install migration-assistant" }, usageExample: "migration-assistant generate --from v1 --to v2 --safe", stars: 923, downloads: 15700 },
  { id: "api-mock-server", name: "API Mock Server", description: "Instantly creates mock API servers from OpenAPI specs or natural language with realistic fake data.", author: "mockdev", tags: ["mock", "api", "testing"], supportedTools: ["Claude Code", "Cursor", "Gemini CLI"], language: "TypeScript", category: "testing", installCommands: { "Claude Code": "claude skill install api-mock-server", "Cursor": "cursor ext install api-mock-server", "Gemini CLI": "gemini install api-mock-server" }, usageExample: "api-mock-server start --spec openapi.yaml --port 3001", stars: 1156, downloads: 20300 },
  { id: "git-workflow", name: "Git Workflow Automator", description: "Automates git workflows including branch naming, commit messages, PR templates, and changelog generation.", author: "gitpro", tags: ["git", "workflow", "automation"], supportedTools: ["Claude Code", "Codex CLI", "Antigravity"], language: "Multi", category: "devops", installCommands: { "Claude Code": "claude skill install git-workflow", "Codex CLI": "codex install git-workflow", "Antigravity": "ag install git-workflow" }, usageExample: "git-workflow commit --type feat --scope auth --auto-msg", stars: 1345, downloads: 23400 },
  { id: "type-inferrer", name: "Type Inferrer", description: "Infers and adds TypeScript types to untyped JavaScript code, including complex generics and utility types.", author: "typewiz", tags: ["typescript", "types", "inference"], supportedTools: ["Claude Code", "Cursor"], language: "TypeScript", category: "refactoring", installCommands: { "Claude Code": "claude skill install type-inferrer", "Cursor": "cursor ext install type-inferrer" }, usageExample: "type-inferrer convert --dir src/ --strict", stars: 987, downloads: 17800 },
  { id: "docker-composer", name: "Docker Compose Builder", description: "Generates Docker and docker-compose configurations from project structure with multi-stage builds and health checks.", author: "containerdev", tags: ["docker", "containers", "compose"], supportedTools: ["Claude Code", "Codex CLI", "Gemini CLI"], language: "Multi", category: "devops", installCommands: { "Claude Code": "claude skill install docker-composer", "Codex CLI": "codex install docker-composer", "Gemini CLI": "gemini install docker-composer" }, usageExample: "docker-composer generate --project . --env production", stars: 1678, downloads: 29100 },
  { id: "error-boundary-gen", name: "Error Boundary Generator", description: "Creates comprehensive error boundaries, fallback UIs, and error reporting for React applications.", author: "reactpro", tags: ["react", "error-handling", "ui"], supportedTools: ["Claude Code", "Cursor"], language: "TypeScript", category: "code-generation", installCommands: { "Claude Code": "claude skill install error-boundary-gen", "Cursor": "cursor ext install error-boundary-gen" }, usageExample: "error-boundary-gen create --app src/App.tsx --sentry", stars: 456, downloads: 7200 },
  { id: "schema-validator", name: "Schema Validator Builder", description: "Creates Zod, Yup, or Joi validation schemas from TypeScript interfaces or JSON examples.", author: "validatedev", tags: ["validation", "schema", "zod"], supportedTools: ["Claude Code", "Cursor", "Antigravity"], language: "TypeScript", category: "code-generation", installCommands: { "Claude Code": "claude skill install schema-validator", "Cursor": "cursor ext install schema-validator", "Antigravity": "ag install schema-validator" }, usageExample: "schema-validator from-type --file types.ts --lib zod", stars: 789, downloads: 12400 },
  { id: "log-analyzer", name: "Log Analyzer", description: "Parses and analyzes application logs to identify patterns, anomalies, and correlate errors across services.", author: "logmaster", tags: ["logging", "analysis", "monitoring"], supportedTools: ["Claude Code", "Codex CLI"], language: "Python", category: "debugging", installCommands: { "Claude Code": "claude skill install log-analyzer", "Codex CLI": "codex install log-analyzer" }, usageExample: "log-analyzer parse --file app.log --pattern errors --last 24h", stars: 634, downloads: 10100 },
  { id: "readme-gen", name: "README Generator", description: "Generates beautiful README files with badges, installation guides, API docs, and contribution guidelines.", author: "docsdev", tags: ["readme", "documentation", "markdown"], supportedTools: ["Claude Code", "Cursor", "Codex CLI", "Gemini CLI"], language: "Multi", category: "documentation", installCommands: { "Claude Code": "claude skill install readme-gen", "Cursor": "cursor ext install readme-gen", "Codex CLI": "codex install readme-gen", "Gemini CLI": "gemini install readme-gen" }, usageExample: "readme-gen create --project . --badges --toc", stars: 1567, downloads: 26800 },
  { id: "env-manager", name: "Environment Manager", description: "Manages environment variables across environments with validation, secret rotation, and .env file generation.", author: "envpro", tags: ["environment", "secrets", "config"], supportedTools: ["Claude Code", "Codex CLI"], language: "Multi", category: "devops", installCommands: { "Claude Code": "claude skill install env-manager", "Codex CLI": "codex install env-manager" }, usageExample: "env-manager sync --from .env.example --to .env.production", stars: 423, downloads: 6800 },
  { id: "component-gen", name: "React Component Generator", description: "Generates React components with props, hooks, styling, tests, and Storybook stories from descriptions.", author: "uicraft", tags: ["react", "components", "generation"], supportedTools: ["Claude Code", "Cursor", "Antigravity"], language: "TypeScript", category: "code-generation", installCommands: { "Claude Code": "claude skill install component-gen", "Cursor": "cursor ext install component-gen", "Antigravity": "ag install component-gen" }, usageExample: "component-gen create DataTable --props columns,data --hooks useMemo", stars: 1890, downloads: 33400, featured: true },
  { id: "dependency-auditor", name: "Dependency Auditor", description: "Audits npm/pip/cargo dependencies for vulnerabilities, license compliance, and update recommendations.", author: "auditdev", tags: ["dependencies", "audit", "security"], supportedTools: ["Claude Code", "Cursor", "Codex CLI"], language: "Multi", category: "security", installCommands: { "Claude Code": "claude skill install dependency-auditor", "Cursor": "cursor ext install dependency-auditor", "Codex CLI": "codex install dependency-auditor" }, usageExample: "dependency-auditor scan --check-licenses --severity high", stars: 1234, downloads: 21500 },
  { id: "cron-builder", name: "Cron Expression Builder", description: "Converts natural language scheduling descriptions into cron expressions with validation and next-run preview.", author: "scheduledev", tags: ["cron", "scheduling", "automation"], supportedTools: ["Claude Code", "Cursor"], language: "Multi", category: "code-generation", installCommands: { "Claude Code": "claude skill install cron-builder", "Cursor": "cursor ext install cron-builder" }, usageExample: "cron-builder 'every weekday at 9am EST'", stars: 345, downloads: 5400 },
  { id: "feature-flag-setup", name: "Feature Flag Setup", description: "Implements feature flags with LaunchDarkly, Unleash, or custom solutions including A/B testing support.", author: "flagdev", tags: ["feature-flags", "a/b-testing", "rollout"], supportedTools: ["Claude Code", "Cursor", "Gemini CLI"], language: "TypeScript", category: "architecture", installCommands: { "Claude Code": "claude skill install feature-flag-setup", "Cursor": "cursor ext install feature-flag-setup", "Gemini CLI": "gemini install feature-flag-setup" }, usageExample: "feature-flag-setup init --provider custom --framework react", stars: 567, downloads: 8900 },
  { id: "graphql-resolver-gen", name: "GraphQL Resolver Generator", description: "Generates type-safe GraphQL resolvers with DataLoader patterns, auth guards, and N+1 query prevention.", author: "gqldev", tags: ["graphql", "resolvers", "api"], supportedTools: ["Claude Code", "Codex CLI"], language: "TypeScript", category: "code-generation", installCommands: { "Claude Code": "claude skill install graphql-resolver-gen", "Codex CLI": "codex install graphql-resolver-gen" }, usageExample: "graphql-resolver-gen --schema schema.graphql --orm prisma", stars: 876, downloads: 14300 },
  { id: "accessibility-checker", name: "Accessibility Checker", description: "Audits web components for WCAG 2.1 AA/AAA compliance with fix suggestions and ARIA attribute generation.", author: "a11ydev", tags: ["accessibility", "wcag", "a11y"], supportedTools: ["Claude Code", "Cursor", "Antigravity"], language: "TypeScript", category: "testing", installCommands: { "Claude Code": "claude skill install accessibility-checker", "Cursor": "cursor ext install accessibility-checker", "Antigravity": "ag install accessibility-checker" }, usageExample: "accessibility-checker scan --dir src/components/ --level AA", stars: 1023, downloads: 17600 },
  { id: "state-machine-gen", name: "State Machine Generator", description: "Creates XState state machines from natural language workflow descriptions with visualization.", author: "statedev", tags: ["state-machine", "xstate", "workflow"], supportedTools: ["Claude Code", "Cursor"], language: "TypeScript", category: "architecture", installCommands: { "Claude Code": "claude skill install state-machine-gen", "Cursor": "cursor ext install state-machine-gen" }, usageExample: "state-machine-gen create 'order: pending -> paid -> shipped -> delivered'", stars: 678, downloads: 10900 },
  { id: "websocket-setup", name: "WebSocket Setup", description: "Sets up WebSocket servers and clients with room management, authentication, reconnection, and message typing.", author: "realtimedev", tags: ["websocket", "realtime", "socket"], supportedTools: ["Claude Code", "Codex CLI"], language: "TypeScript", category: "code-generation", installCommands: { "Claude Code": "claude skill install websocket-setup", "Codex CLI": "codex install websocket-setup" }, usageExample: "websocket-setup create --rooms chat,notifications --auth jwt", stars: 543, downloads: 8700 },
  { id: "rate-limiter", name: "Rate Limiter Setup", description: "Implements rate limiting with Redis or in-memory backends, sliding windows, and per-endpoint configuration.", author: "apidev", tags: ["rate-limiting", "api", "security"], supportedTools: ["Claude Code", "Cursor", "Codex CLI"], language: "Python", category: "security", installCommands: { "Claude Code": "claude skill install rate-limiter", "Cursor": "cursor ext install rate-limiter", "Codex CLI": "codex install rate-limiter" }, usageExample: "rate-limiter setup --backend redis --window 60s --max 100", stars: 712, downloads: 11200 },
  { id: "monorepo-setup", name: "Monorepo Setup", description: "Configures Turborepo or Nx monorepos with shared packages, workspace dependencies, and build caching.", author: "monodev", tags: ["monorepo", "turborepo", "nx"], supportedTools: ["Claude Code", "Codex CLI", "Gemini CLI"], language: "TypeScript", category: "architecture", installCommands: { "Claude Code": "claude skill install monorepo-setup", "Codex CLI": "codex install monorepo-setup", "Gemini CLI": "gemini install monorepo-setup" }, usageExample: "monorepo-setup init --tool turborepo --packages web,api,shared", stars: 1345, downloads: 22800 },
  { id: "csv-analyzer", name: "CSV Data Analyzer", description: "Analyzes CSV/Excel files with statistical summaries, data quality reports, and visualization suggestions.", author: "datadev", tags: ["csv", "analysis", "pandas"], supportedTools: ["Claude Code", "Codex CLI"], language: "Python", category: "data", installCommands: { "Claude Code": "claude skill install csv-analyzer", "Codex CLI": "codex install csv-analyzer" }, usageExample: "csv-analyzer analyze --file data.csv --stats --quality-report", stars: 567, downloads: 9100 },
  { id: "i18n-setup", name: "i18n Setup", description: "Configures internationalization with message extraction, translation file generation, and runtime locale switching.", author: "globaldev", tags: ["i18n", "localization", "translation"], supportedTools: ["Claude Code", "Cursor", "Antigravity"], language: "TypeScript", category: "code-generation", installCommands: { "Claude Code": "claude skill install i18n-setup", "Cursor": "cursor ext install i18n-setup", "Antigravity": "ag install i18n-setup" }, usageExample: "i18n-setup init --locales en,es,fr,de --framework react-intl", stars: 834, downloads: 13800 },
  { id: "load-tester", name: "Load Test Generator", description: "Creates k6 or Artillery load test scripts from API specs with realistic data generation and SLA assertions.", author: "loaddev", tags: ["load-testing", "k6", "performance"], supportedTools: ["Claude Code", "Codex CLI"], language: "TypeScript", category: "testing", installCommands: { "Claude Code": "claude skill install load-tester", "Codex CLI": "codex install load-tester" }, usageExample: "load-tester generate --spec openapi.yaml --tool k6 --vus 100", stars: 678, downloads: 10400 },
  { id: "orm-query-builder", name: "ORM Query Builder", description: "Converts natural language to Prisma, SQLAlchemy, or TypeORM queries with proper joins and eager loading.", author: "querydev", tags: ["orm", "prisma", "sqlalchemy"], supportedTools: ["Claude Code", "Cursor", "Gemini CLI"], language: "Multi", category: "data", installCommands: { "Claude Code": "claude skill install orm-query-builder", "Cursor": "cursor ext install orm-query-builder", "Gemini CLI": "gemini install orm-query-builder" }, usageExample: "orm-query-builder 'find users with orders > $100 in last 30 days' --orm prisma", stars: 923, downloads: 15600 },
  { id: "terraform-gen", name: "Terraform Generator", description: "Generates Terraform/OpenTofu IaC from cloud architecture descriptions with modules and state management.", author: "infradev", tags: ["terraform", "iac", "cloud"], supportedTools: ["Claude Code", "Codex CLI", "Gemini CLI"], language: "Multi", category: "devops", installCommands: { "Claude Code": "claude skill install terraform-gen", "Codex CLI": "codex install terraform-gen", "Gemini CLI": "gemini install terraform-gen" }, usageExample: "terraform-gen create --cloud aws --services ec2,rds,s3 --env staging", stars: 1567, downloads: 27200 },
  { id: "code-review-bot", name: "Code Review Bot", description: "Performs automated code reviews with style checking, complexity analysis, and constructive suggestions.", author: "reviewdev", tags: ["code-review", "linting", "quality"], supportedTools: ["Claude Code", "Cursor", "Codex CLI", "Antigravity"], language: "Multi", category: "refactoring", installCommands: { "Claude Code": "claude skill install code-review-bot", "Cursor": "cursor ext install code-review-bot", "Codex CLI": "codex install code-review-bot", "Antigravity": "ag install code-review-bot" }, usageExample: "code-review-bot review --pr 42 --checks complexity,security,style", stars: 1678, downloads: 28900, featured: true },
  { id: "jwt-auth-setup", name: "JWT Auth Setup", description: "Implements complete JWT authentication with refresh tokens, role-based access, and session management.", author: "authdev", tags: ["jwt", "authentication", "rbac"], supportedTools: ["Claude Code", "Cursor", "Codex CLI"], language: "TypeScript", category: "security", installCommands: { "Claude Code": "claude skill install jwt-auth-setup", "Cursor": "cursor ext install jwt-auth-setup", "Codex CLI": "codex install jwt-auth-setup" }, usageExample: "jwt-auth-setup init --refresh --roles admin,user --framework express", stars: 1234, downloads: 21800 },
  { id: "openapi-gen", name: "OpenAPI Spec Generator", description: "Generates OpenAPI 3.1 specs from existing code, route handlers, or natural language API descriptions.", author: "specdev", tags: ["openapi", "swagger", "api-docs"], supportedTools: ["Claude Code", "Codex CLI", "Gemini CLI"], language: "Multi", category: "documentation", installCommands: { "Claude Code": "claude skill install openapi-gen", "Codex CLI": "codex install openapi-gen", "Gemini CLI": "gemini install openapi-gen" }, usageExample: "openapi-gen scan --dir src/routes/ --output openapi.yaml", stars: 945, downloads: 16100 },
  { id: "dead-code-finder", name: "Dead Code Finder", description: "Identifies unused exports, unreachable code, orphaned files, and unused dependencies in your project.", author: "cleandev", tags: ["dead-code", "cleanup", "analysis"], supportedTools: ["Claude Code", "Cursor", "Codex CLI"], language: "TypeScript", category: "refactoring", installCommands: { "Claude Code": "claude skill install dead-code-finder", "Cursor": "cursor ext install dead-code-finder", "Codex CLI": "codex install dead-code-finder" }, usageExample: "dead-code-finder scan --dir src/ --remove-unused-imports", stars: 876, downloads: 14500 },
  { id: "cache-strategy", name: "Cache Strategy Builder", description: "Implements caching strategies with Redis, Memcached, or in-memory with TTL, invalidation, and cache-aside patterns.", author: "cachedev", tags: ["caching", "redis", "performance"], supportedTools: ["Claude Code", "Codex CLI"], language: "Python", category: "performance", installCommands: { "Claude Code": "claude skill install cache-strategy", "Codex CLI": "codex install cache-strategy" }, usageExample: "cache-strategy setup --backend redis --pattern cache-aside --ttl 3600", stars: 645, downloads: 10200 },
  { id: "animation-gen", name: "CSS Animation Generator", description: "Creates complex CSS and Framer Motion animations from natural language descriptions with performance optimization.", author: "animdev", tags: ["animation", "css", "framer-motion"], supportedTools: ["Claude Code", "Cursor"], language: "TypeScript", category: "code-generation", installCommands: { "Claude Code": "claude skill install animation-gen", "Cursor": "cursor ext install animation-gen" }, usageExample: "animation-gen 'staggered card entrance from bottom with spring physics'", stars: 567, downloads: 8900 },
  { id: "webhook-handler", name: "Webhook Handler", description: "Creates webhook endpoints with signature verification, retry logic, idempotency, and event routing.", author: "hookdev", tags: ["webhook", "events", "integration"], supportedTools: ["Claude Code", "Codex CLI", "Gemini CLI"], language: "TypeScript", category: "code-generation", installCommands: { "Claude Code": "claude skill install webhook-handler", "Codex CLI": "codex install webhook-handler", "Gemini CLI": "gemini install webhook-handler" }, usageExample: "webhook-handler create --provider stripe --events payment_intent.succeeded", stars: 789, downloads: 12700 },
  { id: "e2e-playwright", name: "Playwright Test Writer", description: "Generates Playwright end-to-end tests with page objects, fixtures, and visual regression setup.", author: "e2edev", tags: ["playwright", "e2e", "testing"], supportedTools: ["Claude Code", "Cursor", "Codex CLI"], language: "TypeScript", category: "testing", installCommands: { "Claude Code": "claude skill install e2e-playwright", "Cursor": "cursor ext install e2e-playwright", "Codex CLI": "codex install e2e-playwright" }, usageExample: "e2e-playwright generate --flows login,checkout,profile --base-url http://localhost:3000", stars: 1123, downloads: 19200 },
  { id: "prompt-engineer", name: "Prompt Engineer", description: "Helps craft, test, and optimize LLM prompts with A/B testing, token counting, and output validation.", author: "llmdev", tags: ["prompts", "llm", "ai"], supportedTools: ["Claude Code", "Cursor", "Gemini CLI", "Antigravity"], language: "Python", category: "code-generation", installCommands: { "Claude Code": "claude skill install prompt-engineer", "Cursor": "cursor ext install prompt-engineer", "Gemini CLI": "gemini install prompt-engineer", "Antigravity": "ag install prompt-engineer" }, usageExample: "prompt-engineer optimize --prompt prompts/summarize.txt --model gpt-4 --eval accuracy", stars: 2345, downloads: 41200, featured: true },
  { id: "k8s-manifest-gen", name: "Kubernetes Manifest Generator", description: "Creates Kubernetes manifests with deployments, services, ingress, HPA, and Helm charts from descriptions.", author: "k8sdev", tags: ["kubernetes", "k8s", "helm"], supportedTools: ["Claude Code", "Codex CLI"], language: "Multi", category: "devops", installCommands: { "Claude Code": "claude skill install k8s-manifest-gen", "Codex CLI": "codex install k8s-manifest-gen" }, usageExample: "k8s-manifest-gen create --app web-api --replicas 3 --hpa --ingress", stars: 1456, downloads: 25100 },
  { id: "responsive-converter", name: "Responsive Converter", description: "Converts desktop-first CSS/components to responsive mobile-first with breakpoint analysis and container queries.", author: "cssdev", tags: ["responsive", "mobile", "css"], supportedTools: ["Claude Code", "Cursor"], language: "TypeScript", category: "refactoring", installCommands: { "Claude Code": "claude skill install responsive-converter", "Cursor": "cursor ext install responsive-converter" }, usageExample: "responsive-converter convert --dir src/components/ --approach mobile-first", stars: 456, downloads: 7300 },
  { id: "changelog-gen", name: "Changelog Generator", description: "Generates changelogs from git history with conventional commits, semantic versioning, and release notes.", author: "releasedev", tags: ["changelog", "versioning", "releases"], supportedTools: ["Claude Code", "Codex CLI", "Antigravity"], language: "Multi", category: "documentation", installCommands: { "Claude Code": "claude skill install changelog-gen", "Codex CLI": "codex install changelog-gen", "Antigravity": "ag install changelog-gen" }, usageExample: "changelog-gen generate --from v1.2.0 --to HEAD --format keep-a-changelog", stars: 567, downloads: 9200 },
];

export const allTags = Array.from(new Set(skills.flatMap((s) => s.tags))).sort();
export const allCategories = Array.from(new Set(skills.map((s) => s.category))).sort();
export const allTools: string[] = ["Claude Code", "Cursor", "Codex CLI", "Gemini CLI", "Antigravity"];
export const allLanguages = Array.from(new Set(skills.map((s) => s.language))).sort();
export const featuredSkills = skills.filter((s) => s.featured);

export function searchSkills(query: string, filters?: { tool?: string; category?: string; language?: string }): Skill[] {
  let results = skills;
  if (query) {
    const q = query.toLowerCase();
    results = results.filter(
      (s) =>
        s.name.toLowerCase().includes(q) ||
        s.description.toLowerCase().includes(q) ||
        s.tags.some((t) => t.toLowerCase().includes(q))
    );
  }
  if (filters?.tool) results = results.filter((s) => s.supportedTools.includes(filters.tool as any));
  if (filters?.category) results = results.filter((s) => s.category === filters.category);
  if (filters?.language) results = results.filter((s) => s.language === filters.language);
  return results;
}

export function getSkillById(id: string): Skill | undefined {
  return skills.find((s) => s.id === id);
}

export function getAutocompleteSuggestions(query: string): string[] {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase();
  const names = skills.filter((s) => s.name.toLowerCase().includes(q)).map((s) => s.name);
  const tags = allTags.filter((t) => t.includes(q));
  return [...new Set([...names, ...tags])].slice(0, 8);
}
